export { default as HomePreview } from './Home/HomePreview';
export { default as HomeDataCentres } from './Home/HomeDataCentres';
export { default as HomeRoadmap } from './Home/HomeRoadmap';
export { default as HomePartners } from './Home/HomePartners';
export { default as HomeLinks } from './Home/HomeLinks';
export { default as HomeNews } from './Home/HomeNews';
export { default as StakingInfo } from './Staking/StakingInfo';
export { default as AboutContacts } from './About/AboutContacts';
export { default as AboutTeam } from './About/AboutTeam';
